FROM httpd:2.4
ADD website.tar.gz /usr/local/apache2/htdocs/

#ADD supports remote URLs (but probably shouldnt use it), and it also supports the use of tar files
#(will extract the content and copy it inside the image)